/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ModuleModelService } from "../moduleModel.service";
import { ModuleModelCreateInput } from "./ModuleModelCreateInput";
import { ModuleModelWhereInput } from "./ModuleModelWhereInput";
import { ModuleModelWhereUniqueInput } from "./ModuleModelWhereUniqueInput";
import { ModuleModelFindManyArgs } from "./ModuleModelFindManyArgs";
import { ModuleModelUpdateInput } from "./ModuleModelUpdateInput";
import { ModuleModel } from "./ModuleModel";

export class ModuleModelGrpcControllerBase {
  constructor(protected readonly service: ModuleModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ModuleModel })
  @GrpcMethod("ModuleModelService", "createModuleModel")
  async createModuleModel(
    @common.Body() data: ModuleModelCreateInput
  ): Promise<ModuleModel> {
    return await this.service.createModuleModel({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ModuleModel] })
  @ApiNestedQuery(ModuleModelFindManyArgs)
  @GrpcMethod("ModuleModelService", "moduleModels")
  async moduleModels(@common.Req() request: Request): Promise<ModuleModel[]> {
    const args = plainToClass(ModuleModelFindManyArgs, request.query);
    return this.service.moduleModels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModuleModelService", "moduleModel")
  async moduleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    const result = await this.service.moduleModel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModuleModelService", "updateModuleModel")
  async updateModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput,
    @common.Body() data: ModuleModelUpdateInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.updateModuleModel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ModuleModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ModuleModelService", "deleteModuleModel")
  async deleteModuleModel(
    @common.Param() params: ModuleModelWhereUniqueInput
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.deleteModuleModel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
