/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CurrentUtilityTariff } from "./CurrentUtilityTariff";
import { CurrentUtilityTariffCountArgs } from "./CurrentUtilityTariffCountArgs";
import { CurrentUtilityTariffFindManyArgs } from "./CurrentUtilityTariffFindManyArgs";
import { CurrentUtilityTariffFindUniqueArgs } from "./CurrentUtilityTariffFindUniqueArgs";
import { DeleteCurrentUtilityTariffArgs } from "./DeleteCurrentUtilityTariffArgs";
import { CurrentUtilityTariffService } from "../currentUtilityTariff.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CurrentUtilityTariff)
export class CurrentUtilityTariffResolverBase {
  constructor(
    protected readonly service: CurrentUtilityTariffService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CurrentUtilityTariff",
    action: "read",
    possession: "any",
  })
  async _currentUtilityTariffsMeta(
    @graphql.Args() args: CurrentUtilityTariffCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CurrentUtilityTariff])
  @nestAccessControl.UseRoles({
    resource: "CurrentUtilityTariff",
    action: "read",
    possession: "any",
  })
  async currentUtilityTariffs(
    @graphql.Args() args: CurrentUtilityTariffFindManyArgs
  ): Promise<CurrentUtilityTariff[]> {
    return this.service.currentUtilityTariffs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CurrentUtilityTariff, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CurrentUtilityTariff",
    action: "read",
    possession: "own",
  })
  async currentUtilityTariff(
    @graphql.Args() args: CurrentUtilityTariffFindUniqueArgs
  ): Promise<CurrentUtilityTariff | null> {
    const result = await this.service.currentUtilityTariff(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CurrentUtilityTariff)
  @nestAccessControl.UseRoles({
    resource: "CurrentUtilityTariff",
    action: "delete",
    possession: "any",
  })
  async deleteCurrentUtilityTariff(
    @graphql.Args() args: DeleteCurrentUtilityTariffArgs
  ): Promise<CurrentUtilityTariff | null> {
    try {
      return await this.service.deleteCurrentUtilityTariff(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
