/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { AssignedContactService } from "../assignedContact.service";
import { AssignedContactCreateInput } from "./AssignedContactCreateInput";
import { AssignedContactWhereInput } from "./AssignedContactWhereInput";
import { AssignedContactWhereUniqueInput } from "./AssignedContactWhereUniqueInput";
import { AssignedContactFindManyArgs } from "./AssignedContactFindManyArgs";
import { AssignedContactUpdateInput } from "./AssignedContactUpdateInput";
import { AssignedContact } from "./AssignedContact";

export class AssignedContactGrpcControllerBase {
  constructor(protected readonly service: AssignedContactService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssignedContact })
  @GrpcMethod("AssignedContactService", "createAssignedContact")
  async createAssignedContact(
    @common.Body() data: AssignedContactCreateInput
  ): Promise<AssignedContact> {
    return await this.service.createAssignedContact({
      data: {
        ...data,

        contact: data.contact
          ? {
              connect: data.contact,
            }
          : undefined,
      },
      select: {
        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AssignedContact] })
  @ApiNestedQuery(AssignedContactFindManyArgs)
  @GrpcMethod("AssignedContactService", "assignedContacts")
  async assignedContacts(
    @common.Req() request: Request
  ): Promise<AssignedContact[]> {
    const args = plainToClass(AssignedContactFindManyArgs, request.query);
    return this.service.assignedContacts({
      ...args,
      select: {
        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssignedContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AssignedContactService", "assignedContact")
  async assignedContact(
    @common.Param() params: AssignedContactWhereUniqueInput
  ): Promise<AssignedContact | null> {
    const result = await this.service.assignedContact({
      where: params,
      select: {
        contact: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssignedContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AssignedContactService", "updateAssignedContact")
  async updateAssignedContact(
    @common.Param() params: AssignedContactWhereUniqueInput,
    @common.Body() data: AssignedContactUpdateInput
  ): Promise<AssignedContact | null> {
    try {
      return await this.service.updateAssignedContact({
        where: params,
        data: {
          ...data,

          contact: data.contact
            ? {
                connect: data.contact,
              }
            : undefined,
        },
        select: {
          contact: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssignedContact })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("AssignedContactService", "deleteAssignedContact")
  async deleteAssignedContact(
    @common.Param() params: AssignedContactWhereUniqueInput
  ): Promise<AssignedContact | null> {
    try {
      return await this.service.deleteAssignedContact({
        where: params,
        select: {
          contact: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
