/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UtilityTariff } from "./UtilityTariff";
import { UtilityTariffCountArgs } from "./UtilityTariffCountArgs";
import { UtilityTariffFindManyArgs } from "./UtilityTariffFindManyArgs";
import { UtilityTariffFindUniqueArgs } from "./UtilityTariffFindUniqueArgs";
import { DeleteUtilityTariffArgs } from "./DeleteUtilityTariffArgs";
import { UtilityTariffService } from "../utilityTariff.service";
@graphql.Resolver(() => UtilityTariff)
export class UtilityTariffResolverBase {
  constructor(protected readonly service: UtilityTariffService) {}

  async _utilityTariffsMeta(
    @graphql.Args() args: UtilityTariffCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UtilityTariff])
  async utilityTariffs(
    @graphql.Args() args: UtilityTariffFindManyArgs
  ): Promise<UtilityTariff[]> {
    return this.service.utilityTariffs(args);
  }

  @graphql.Query(() => UtilityTariff, { nullable: true })
  async utilityTariff(
    @graphql.Args() args: UtilityTariffFindUniqueArgs
  ): Promise<UtilityTariff | null> {
    const result = await this.service.utilityTariff(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UtilityTariff)
  async deleteUtilityTariff(
    @graphql.Args() args: DeleteUtilityTariffArgs
  ): Promise<UtilityTariff | null> {
    try {
      return await this.service.deleteUtilityTariff(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
