/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PricingScheme } from "./PricingScheme";
import { PricingSchemeCountArgs } from "./PricingSchemeCountArgs";
import { PricingSchemeFindManyArgs } from "./PricingSchemeFindManyArgs";
import { PricingSchemeFindUniqueArgs } from "./PricingSchemeFindUniqueArgs";
import { DeletePricingSchemeArgs } from "./DeletePricingSchemeArgs";
import { PricingSchemeService } from "../pricingScheme.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PricingScheme)
export class PricingSchemeResolverBase {
  constructor(
    protected readonly service: PricingSchemeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PricingScheme",
    action: "read",
    possession: "any",
  })
  async _pricingSchemesMeta(
    @graphql.Args() args: PricingSchemeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PricingScheme])
  @nestAccessControl.UseRoles({
    resource: "PricingScheme",
    action: "read",
    possession: "any",
  })
  async pricingSchemes(
    @graphql.Args() args: PricingSchemeFindManyArgs
  ): Promise<PricingScheme[]> {
    return this.service.pricingSchemes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PricingScheme, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PricingScheme",
    action: "read",
    possession: "own",
  })
  async pricingScheme(
    @graphql.Args() args: PricingSchemeFindUniqueArgs
  ): Promise<PricingScheme | null> {
    const result = await this.service.pricingScheme(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PricingScheme)
  @nestAccessControl.UseRoles({
    resource: "PricingScheme",
    action: "delete",
    possession: "any",
  })
  async deletePricingScheme(
    @graphql.Args() args: DeletePricingSchemeArgs
  ): Promise<PricingScheme | null> {
    try {
      return await this.service.deletePricingScheme(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
