/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PaymentOptionService } from "../paymentOption.service";
import { PaymentOptionCreateInput } from "./PaymentOptionCreateInput";
import { PaymentOption } from "./PaymentOption";
import { PaymentOptionFindManyArgs } from "./PaymentOptionFindManyArgs";
import { PaymentOptionWhereUniqueInput } from "./PaymentOptionWhereUniqueInput";
import { PaymentOptionUpdateInput } from "./PaymentOptionUpdateInput";

export class PaymentOptionControllerBase {
  constructor(protected readonly service: PaymentOptionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentOption })
  async createPaymentOption(
    @common.Body() data: PaymentOptionCreateInput
  ): Promise<PaymentOption> {
    return await this.service.createPaymentOption({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentOption] })
  @ApiNestedQuery(PaymentOptionFindManyArgs)
  async paymentOptions(
    @common.Req() request: Request
  ): Promise<PaymentOption[]> {
    const args = plainToClass(PaymentOptionFindManyArgs, request.query);
    return this.service.paymentOptions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentOption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async paymentOption(
    @common.Param() params: PaymentOptionWhereUniqueInput
  ): Promise<PaymentOption | null> {
    const result = await this.service.paymentOption({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentOption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePaymentOption(
    @common.Param() params: PaymentOptionWhereUniqueInput,
    @common.Body() data: PaymentOptionUpdateInput
  ): Promise<PaymentOption | null> {
    try {
      return await this.service.updatePaymentOption({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentOption })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePaymentOption(
    @common.Param() params: PaymentOptionWhereUniqueInput
  ): Promise<PaymentOption | null> {
    try {
      return await this.service.deletePaymentOption({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
