/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OtherComponent } from "./OtherComponent";
import { OtherComponentCountArgs } from "./OtherComponentCountArgs";
import { OtherComponentFindManyArgs } from "./OtherComponentFindManyArgs";
import { OtherComponentFindUniqueArgs } from "./OtherComponentFindUniqueArgs";
import { DeleteOtherComponentArgs } from "./DeleteOtherComponentArgs";
import { OtherComponentService } from "../otherComponent.service";
@graphql.Resolver(() => OtherComponent)
export class OtherComponentResolverBase {
  constructor(protected readonly service: OtherComponentService) {}

  async _otherComponentsMeta(
    @graphql.Args() args: OtherComponentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OtherComponent])
  async otherComponents(
    @graphql.Args() args: OtherComponentFindManyArgs
  ): Promise<OtherComponent[]> {
    return this.service.otherComponents(args);
  }

  @graphql.Query(() => OtherComponent, { nullable: true })
  async otherComponent(
    @graphql.Args() args: OtherComponentFindUniqueArgs
  ): Promise<OtherComponent | null> {
    const result = await this.service.otherComponent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OtherComponent)
  async deleteOtherComponent(
    @graphql.Args() args: DeleteOtherComponentArgs
  ): Promise<OtherComponent | null> {
    try {
      return await this.service.deleteOtherComponent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
