/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CurrentUtilityTariff as PrismaCurrentUtilityTariff,
} from "@prisma/client";

export class CurrentUtilityTariffServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CurrentUtilityTariffCountArgs, "select">
  ): Promise<number> {
    return this.prisma.currentUtilityTariff.count(args);
  }

  async currentUtilityTariffs<
    T extends Prisma.CurrentUtilityTariffFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CurrentUtilityTariffFindManyArgs>
  ): Promise<PrismaCurrentUtilityTariff[]> {
    return this.prisma.currentUtilityTariff.findMany<Prisma.CurrentUtilityTariffFindManyArgs>(
      args
    );
  }
  async currentUtilityTariff<
    T extends Prisma.CurrentUtilityTariffFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CurrentUtilityTariffFindUniqueArgs>
  ): Promise<PrismaCurrentUtilityTariff | null> {
    return this.prisma.currentUtilityTariff.findUnique(args);
  }
  async createCurrentUtilityTariff<
    T extends Prisma.CurrentUtilityTariffCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CurrentUtilityTariffCreateArgs>
  ): Promise<PrismaCurrentUtilityTariff> {
    return this.prisma.currentUtilityTariff.create<T>(args);
  }
  async updateCurrentUtilityTariff<
    T extends Prisma.CurrentUtilityTariffUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CurrentUtilityTariffUpdateArgs>
  ): Promise<PrismaCurrentUtilityTariff> {
    return this.prisma.currentUtilityTariff.update<T>(args);
  }
  async deleteCurrentUtilityTariff<
    T extends Prisma.CurrentUtilityTariffDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CurrentUtilityTariffDeleteArgs>
  ): Promise<PrismaCurrentUtilityTariff> {
    return this.prisma.currentUtilityTariff.delete(args);
  }
}
