/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DocumentTemplate } from "./DocumentTemplate";
import { DocumentTemplateCountArgs } from "./DocumentTemplateCountArgs";
import { DocumentTemplateFindManyArgs } from "./DocumentTemplateFindManyArgs";
import { DocumentTemplateFindUniqueArgs } from "./DocumentTemplateFindUniqueArgs";
import { DeleteDocumentTemplateArgs } from "./DeleteDocumentTemplateArgs";
import { DocumentTemplateService } from "../documentTemplate.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DocumentTemplate)
export class DocumentTemplateResolverBase {
  constructor(
    protected readonly service: DocumentTemplateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DocumentTemplate",
    action: "read",
    possession: "any",
  })
  async _documentTemplatesMeta(
    @graphql.Args() args: DocumentTemplateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DocumentTemplate])
  @nestAccessControl.UseRoles({
    resource: "DocumentTemplate",
    action: "read",
    possession: "any",
  })
  async documentTemplates(
    @graphql.Args() args: DocumentTemplateFindManyArgs
  ): Promise<DocumentTemplate[]> {
    return this.service.documentTemplates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DocumentTemplate, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DocumentTemplate",
    action: "read",
    possession: "own",
  })
  async documentTemplate(
    @graphql.Args() args: DocumentTemplateFindUniqueArgs
  ): Promise<DocumentTemplate | null> {
    const result = await this.service.documentTemplate(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DocumentTemplate)
  @nestAccessControl.UseRoles({
    resource: "DocumentTemplate",
    action: "delete",
    possession: "any",
  })
  async deleteDocumentTemplate(
    @graphql.Args() args: DeleteDocumentTemplateArgs
  ): Promise<DocumentTemplate | null> {
    try {
      return await this.service.deleteDocumentTemplate(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
