/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProposedUtilityTariff } from "./ProposedUtilityTariff";
import { ProposedUtilityTariffCountArgs } from "./ProposedUtilityTariffCountArgs";
import { ProposedUtilityTariffFindManyArgs } from "./ProposedUtilityTariffFindManyArgs";
import { ProposedUtilityTariffFindUniqueArgs } from "./ProposedUtilityTariffFindUniqueArgs";
import { DeleteProposedUtilityTariffArgs } from "./DeleteProposedUtilityTariffArgs";
import { ProposedUtilityTariffService } from "../proposedUtilityTariff.service";
@graphql.Resolver(() => ProposedUtilityTariff)
export class ProposedUtilityTariffResolverBase {
  constructor(protected readonly service: ProposedUtilityTariffService) {}

  async _proposedUtilityTariffsMeta(
    @graphql.Args() args: ProposedUtilityTariffCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProposedUtilityTariff])
  async proposedUtilityTariffs(
    @graphql.Args() args: ProposedUtilityTariffFindManyArgs
  ): Promise<ProposedUtilityTariff[]> {
    return this.service.proposedUtilityTariffs(args);
  }

  @graphql.Query(() => ProposedUtilityTariff, { nullable: true })
  async proposedUtilityTariff(
    @graphql.Args() args: ProposedUtilityTariffFindUniqueArgs
  ): Promise<ProposedUtilityTariff | null> {
    const result = await this.service.proposedUtilityTariff(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProposedUtilityTariff)
  async deleteProposedUtilityTariff(
    @graphql.Args() args: DeleteProposedUtilityTariffArgs
  ): Promise<ProposedUtilityTariff | null> {
    try {
      return await this.service.deleteProposedUtilityTariff(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
