/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProposedUtilityTariffService } from "../proposedUtilityTariff.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProposedUtilityTariffCreateInput } from "./ProposedUtilityTariffCreateInput";
import { ProposedUtilityTariff } from "./ProposedUtilityTariff";
import { ProposedUtilityTariffFindManyArgs } from "./ProposedUtilityTariffFindManyArgs";
import { ProposedUtilityTariffWhereUniqueInput } from "./ProposedUtilityTariffWhereUniqueInput";
import { ProposedUtilityTariffUpdateInput } from "./ProposedUtilityTariffUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProposedUtilityTariffControllerBase {
  constructor(
    protected readonly service: ProposedUtilityTariffService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProposedUtilityTariff })
  @nestAccessControl.UseRoles({
    resource: "ProposedUtilityTariff",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProposedUtilityTariff(
    @common.Body() data: ProposedUtilityTariffCreateInput
  ): Promise<ProposedUtilityTariff> {
    return await this.service.createProposedUtilityTariff({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProposedUtilityTariff] })
  @ApiNestedQuery(ProposedUtilityTariffFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProposedUtilityTariff",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proposedUtilityTariffs(
    @common.Req() request: Request
  ): Promise<ProposedUtilityTariff[]> {
    const args = plainToClass(ProposedUtilityTariffFindManyArgs, request.query);
    return this.service.proposedUtilityTariffs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProposedUtilityTariff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProposedUtilityTariff",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async proposedUtilityTariff(
    @common.Param() params: ProposedUtilityTariffWhereUniqueInput
  ): Promise<ProposedUtilityTariff | null> {
    const result = await this.service.proposedUtilityTariff({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProposedUtilityTariff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProposedUtilityTariff",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProposedUtilityTariff(
    @common.Param() params: ProposedUtilityTariffWhereUniqueInput,
    @common.Body() data: ProposedUtilityTariffUpdateInput
  ): Promise<ProposedUtilityTariff | null> {
    try {
      return await this.service.updateProposedUtilityTariff({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProposedUtilityTariff })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProposedUtilityTariff",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProposedUtilityTariff(
    @common.Param() params: ProposedUtilityTariffWhereUniqueInput
  ): Promise<ProposedUtilityTariff | null> {
    try {
      return await this.service.deleteProposedUtilityTariff({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
