/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Inverter } from "./Inverter";
import { InverterCountArgs } from "./InverterCountArgs";
import { InverterFindManyArgs } from "./InverterFindManyArgs";
import { InverterFindUniqueArgs } from "./InverterFindUniqueArgs";
import { DeleteInverterArgs } from "./DeleteInverterArgs";
import { InverterService } from "../inverter.service";
@graphql.Resolver(() => Inverter)
export class InverterResolverBase {
  constructor(protected readonly service: InverterService) {}

  async _invertersMeta(
    @graphql.Args() args: InverterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Inverter])
  async inverters(
    @graphql.Args() args: InverterFindManyArgs
  ): Promise<Inverter[]> {
    return this.service.inverters(args);
  }

  @graphql.Query(() => Inverter, { nullable: true })
  async inverter(
    @graphql.Args() args: InverterFindUniqueArgs
  ): Promise<Inverter | null> {
    const result = await this.service.inverter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inverter)
  async deleteInverter(
    @graphql.Args() args: DeleteInverterArgs
  ): Promise<Inverter | null> {
    try {
      return await this.service.deleteInverter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
